import React from 'react'
import Header from '../Components/Header'
import Fotter from '../Components/Fotter'

function PrivacyPolicy() {
  return (
    <div> <Header/>  <div className="flex flex-col justify-center my-20 items-center  gap-[12px]">
          <h2 className="md:text-[48px] text-[26px] font-DMSans font-medium text-center text-tertiary">
         Privacy Policy
          </h2>
      
          <p className=" w-[77%] text-center md:text-[18px] pt-10 text-[14px] font-DMSans font-extra-light  text-[#666666]">
          This Privacy Policy describes Our policies and procedures on the collection, use and disclosure of Your information when You respond to our advertisements and tells You about Your privacy rights and how the law protects You. We use Your Personal Data to contact and support you, as well as to provide and improve the Service. By using the Service, You agree to the collection and use of information in accordance with this Privacy Policy.

          </p>
              <h3 className='md:text-[30px] text-[20px] mt-16 font-DMSans font-medium text-center text-tertiary'>
          Interpretation and Definitions
          </h3>
          <h4 className='md:text-[20px] text-[15px] font-DMSans font-medium text-center text-tertiary'>Interpretation</h4>
            <p className=" w-[77%] text-center md:text-[18px]  text-[14px] font-DMSans font-extra-light  text-[#666666]">
       The words of which the initial letter is capitalized have meanings defined under the following conditions. The following definitions shall have the same meaning regardless of whether they appear in singular or in plural.

          </p>
          <h4 className='md:text-[20px] text-[15px] mt-5 font-DMSans font-medium text-center text-tertiary'>Definitions</h4>
            <p className=" w-[77%] text-center md:text-[18px]  text-[14px] font-DMSans font-extra-light  text-[#666666]">
      For the purposes of this Privacy Policy:<br/><br/><br/>
      Company (referred to as either “the Company”, “We”, “Us” or “Our” in this Agreement) refers to CA DR. MANISH GUPTA.<br/><br/>
Device means any device that can access the Service such as a computer, a cellphone or a digital tablet.<br/><br/>
Personal Data is any information that relates to an identified or identifiable individual.<br/><br/>
Service refers to the advertisement, website, or application.<br/><br/>
Service Provider means any natural or legal person who processes the data on behalf of the Company. It refers to third-party companies or individuals employed by the Company to facilitate the Service, to provide the Service on behalf of the Company, to perform services related to the Service or to assist the Company in analyzing how the Service is used.<br/><br/>
Usage Data refers to data collected automatically, either generated by the use of the Service or from the Service infrastructure itself (for example, the duration of a page visit).<br/><br/>
You means the individual accessing or using the Service, or the company, or other legal entity on behalf of which such individual is accessing or using the Service, as applicable.

          </p>



{/* Collecting and Using Your Personal Data */}
              <h3 className='md:text-[30px] text-[20px] mt-16 font-DMSans font-medium text-center text-tertiary'>
         Collecting and Using Your Personal Data
          </h3>
          <h4 className='md:text-[20px] text-[15px] font-DMSans font-medium text-center text-tertiary'>Personal Data</h4>
            <p className=" w-[77%] text-center md:text-[18px]  text-[14px] font-DMSans font-extra-light  text-[#666666]">
      While using Our Service, We may ask You to provide Us with certain personally identifiable information that can be used to contact or identify You. Personally identifiable information may include, but is not limited to:<br/><br/>

      First name and last name<br/>
Email address<br/>
Phone number<br/>
Location details such as your address, city, or country<br/>
Any other data such as personal preferences, requirements, or comments<br/>
          </p>
          <h4 className='md:text-[20px] text-[15px] mt-5 font-DMSans font-medium text-center text-tertiary'>Use of Your Personal Data</h4>
            <p className=" w-[77%] text-center md:text-[18px]  text-[14px] font-DMSans font-extra-light  text-[#666666]">
  The Company may use Personal Data for the following purposes:<br/><br/><br/>

To provide and maintain our Service, including to monitor the usage of our Service.<br/><br/>
To manage Your Account: to manage Your registration as a user of the Service. The Personal Data You provide can give You access to different functionalities of the Service that are available to You as a registered user.
<br/><br/>For the performance of a contract: the development, compliance and undertaking of the purchase contract for the products, items or services You have purchased or of any other contract with Us through the Service.
<br/><br/>To contact You: To contact You by email, telephone calls, SMS, or other equivalent forms of electronic communication, such as a mobile application’s push notifications regarding updates or informative communications related to the functionalities, products or contracted services, including the security updates, when necessary or reasonable for their implementation.<br/><br/>
To provide You with news, special offers and general information about other goods, services and events which we offer that are similar to those that you have already purchased or enquired about unless You have opted not to receive such information.<br/><br/>
To manage Your requests: To attend and manage Your requests to Us.<br/><br/>
For business transfers: We may use Your information to evaluate or conduct a merger, divestiture, restructuring, reorganization, dissolution, or other sale or transfer of some or all of Our assets, whether as a going concern or as part of bankruptcy, liquidation, or similar proceeding, in which Personal Data held by Us about our Service users is among the assets transferred.<br/><br/>
For other purposes: We may use Your information for other purposes, such as data analysis, identifying usage trends, determining the effectiveness of our promotional campaigns and to evaluate and improve our Service, products, services, marketing and your experience.<br/><br/>


          </p>
       

        </div>
        <Fotter/></div>
  )
}

export default PrivacyPolicy